version: '3.8'

services:
  service:
    build: ./service
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./service/:/usr/src/app/
    ports:
      - 5001:5000
    env_file:
      - ./service/.env.dev
    depends_on:
      - db
  api_aguas_limpas:
    build: ./api_aguas_limpas
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./api_aguas_limpas/:/usr/src/app/
    ports:
      - 5014:5014
    env_file:
      - ./api_aguas_limpas/.env.dev
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=f01
      - POSTGRES_PASSWORD=f01
      - POSTGRES_DB=f01_dev

volumes:
  postgres_data: