version: '3.8'

services:
  api_aguas_limpas_etl:
    build: ./api_aguas_limpas_etl
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./api_aguas_limpas_etl/:/usr/src/app/
    ports:
      - 5001:5000
    env_file:
      - ./api_aguas_limpas_etl/.env.dev
    depends_on:
      - db
  api_aguas_limpas_back:
    build: ./api_aguas_limpas_back
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./api_aguas_limpas_back/:/usr/src/app/
    ports:
      - 5014:5014
    env_file:
      - ./api_aguas_limpas_back/.env.dev
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=f01
      - POSTGRES_PASSWORD=f01
      - POSTGRES_DB=f01_dev

volumes:
  postgres_data: