import json
from validadores.servidores.dados_dos_servidores import ValidadorDadosDosServidores
from validadores.servidores.registro_da_remuneracao import ValidadorRegistroDaRemuneracao
from validadores.servidores.registro_por_lotação import ValidadorRegistroPorLotação
from validadores.servidores.auxilios import ValidadorAuxilios
from validadores.servidores.proventos_de_aposentadoria import ValidadorproventosDeAposentadoria
from validadores.servidores.proventos_de_pensao import ValidadorProventosDePensao
from validadores.servidores.relatorio_mensal import ValidadorRelatorioMensal
from validadores.servidores.dados_de_remuneracao import ValidadorDadosDeRemuneracao

# Siplanweb
from utilconst.constant_siplanweb import municipios_siplanweb
from utilconst.constant_siplanweb import keywords_siplanweb

def pipeline_servidores(keywords, job_name):
    pass