"""empty message

Revision ID: 15c720adc33a
Revises: 
Create Date: 2022-09-13 15:34:33.020856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15c720adc33a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coletor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('municipio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_ibge', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=30), nullable=False),
    sa.Column('nome_formatado', sa.String(length=30), nullable=True),
    sa.Column('url_site_prefeitura', sa.String(length=50), nullable=True),
    sa.Column('url_portal', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('municipioxempresa',
    sa.Column('id_municipio', sa.Integer(), nullable=True),
    sa.Column('id_empresa', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_empresa'], ['empresa.id'], ),
    sa.ForeignKeyConstraint(['id_municipio'], ['municipio.id'], )
    )
    op.create_table('subtag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=30), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=30), nullable=False),
    sa.Column('subtag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subtag_id'], ['subtag.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resultado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.Integer(), nullable=True),
    sa.Column('subtag_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('municipio_id', sa.Integer(), nullable=True),
    sa.Column('codigo_resposta', sa.String(length=30), nullable=True),
    sa.Column('descricao', sa.String(length=100), nullable=True),
    sa.Column('justificativa', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['municipio_id'], ['municipio.id_ibge'], ),
    sa.ForeignKeyConstraint(['subtag_id'], ['subtag.id'], ),
    sa.ForeignKeyConstraint(['tag'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resultado')
    op.drop_table('item')
    op.drop_table('subtag')
    op.drop_table('municipioxempresa')
    op.drop_table('tag')
    op.drop_table('municipio')
    op.drop_table('empresa')
    op.drop_table('coletor')
    # ### end Alembic commands ###
