"""empty message

Revision ID: 4762641da876
Revises: ef3d872c5bd8
Create Date: 2023-06-13 12:03:46.974394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4762641da876'
down_revision = 'ef3d872c5bd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('municipio', schema=None) as batch_op:
        batch_op.alter_column('url_portal',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=1000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('municipio', schema=None) as batch_op:
        batch_op.alter_column('url_portal',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)

    # ### end Alembic commands ###
