"""empty message

Revision ID: 70c4c056505e
Revises: ba9622a2b443
Create Date: 2023-01-25 17:45:59.095137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70c4c056505e'
down_revision = 'ba9622a2b443'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resultado', sa.Column('data_validacao', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resultado', 'data_validacao')
    # ### end Alembic commands ###
