"""empty message

Revision ID: ef3d872c5bd8
Revises: 7d2099c61225
Create Date: 2023-06-13 12:03:05.133582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef3d872c5bd8'
down_revision = '7d2099c61225'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('municipio', schema=None) as batch_op:
        batch_op.alter_column('url_portal',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('municipio', schema=None) as batch_op:
        batch_op.alter_column('url_portal',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###
